// resources/scripts/components/server/UltimateSuite/VersionSelector.tsx
import React, { useState, ChangeEvent } from 'react';
import axios from 'axios';
import { ServerContext } from '@/state/server';
import { useFlash } from '@/plugins/useFlash';
import Button from '@/components/elements/Button';
import { useTranslation } from 'react-i18next';

const VersionSelector = () => {
    const { t } = useTranslation();
    const { addFlash } = useFlash();
    const uuid = ServerContext.useStoreState((state: any) => state.server.data!.uuid);
    const [type, setType] = useState<string>('paper');
    const [version, setVersion] = useState<string>('');
    const [loading, setLoading] = useState<boolean>(false);

    const updateVersion = () => {
        if (!version) return;
        setLoading(true);
        axios.post(`/api/client/servers/${uuid}/ultimate-suite/version`, { type, version })
            .then(() => addFlash({ type: 'success', key: 'us:v', message: t('ultimate_suite.version.success') }))
            .catch(() => addFlash({ type: 'error', key: 'us:v', message: t('ultimate_suite.version.error') }))
            .finally(() => setLoading(false));
    };

    return (
        <div className={'bg-neutral-800 p-6 rounded shadow-md border border-neutral-700'}>
            <h2 className={'text-xl font-bold mb-4 text-neutral-100'}>{t('ultimate_suite.version.title')}</h2>
            <div className={'grid grid-cols-1 md:grid-cols-2 gap-6'}>
                <select 
                    value={type} 
                    onChange={(e: ChangeEvent<HTMLSelectElement>) => setType(e.target.value)} 
                    className={'bg-neutral-900 border border-neutral-700 text-white p-2 rounded'}
                >
                    <option value="paper">PaperMC</option>
                    <option value="purpur">Purpur</option>
                </select>
                <input 
                    type="text" 
                    value={version} 
                    onChange={(e: ChangeEvent<HTMLInputElement>) => setVersion(e.target.value)} 
                    placeholder="1.20.4" 
                    className={'bg-neutral-900 border border-neutral-700 text-white p-2 rounded'} 
                />
            </div>
            <Button isLoading={loading} disabled={!version} onClick={updateVersion} className={'mt-4 w-full'}>
                {t('ultimate_suite.version.update_btn')}
            </Button>
        </div>
    );
};

export default VersionSelector;

// resources/scripts/extensions/UltimateSuite/components/VersionSelector.vue
<template>
    <div class="version-manager bg-neutral-700 p-6 rounded shadow-md">
        <h2 class="text-xl font-semibold text-neutral-100 mb-4">{{ t('version_manager.title') }}</h2>
        
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
                <label class="block text-sm font-medium text-neutral-300 mb-2">{{ t('version_manager.type') }}</label>
                <select v-model="form.type" class="form-select w-full bg-neutral-800 border-neutral-600 rounded">
                    <option value="paper">Paper</option>
                    <option value="purpur">Purpur</option>
                    <option value="fabric">Fabric</option>
                    <option value="forge">Forge</option>
                </select>
            </div>
            <div>
                <label class="block text-sm font-medium text-neutral-300 mb-2">{{ t('version_manager.version') }}</label>
                <input v-model="form.version" type="text" placeholder="1.20.4" class="form-input w-full bg-neutral-800 border-neutral-600 rounded" />
            </div>
        </div>

        <div class="mt-6 flex justify-end">
            <button 
                @click="updateVersion" 
                :disabled="isUpdating"
                class="btn btn-primary bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded transition-colors"
            >
                {{ isUpdating ? t('version_manager.updating') : t('version_manager.update_btn') }}
            </button>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useI18n } from 'vue-i18n';
import http from '@/api/http';
import { useRoute } from 'vue-router';

const { t } = useI18n();
const route = useRoute();
const serverId = route.params.id; // Pterodactyl uses short UUID in route params

const isUpdating = ref(false);
const form = ref({
    type: 'paper',
    version: ''
});

const updateVersion = async () => {
    if (!form.value.version) return;
    isUpdating.value = true;

    try {
        await http.post(`/api/client/servers/${serverId}/ultimate-suite/version`, form.value);
        alert(t('version_manager.success')); // In Pterodactyl, preferably use the `useFlash` helper
    } catch (error) {
        console.error('Update failed:', error);
    } finally {
        isUpdating.value = false;
    }
};
</script>
