// resources/extensions/UltimateSuite/components/PlayerList.vue
<template>
    <div class="player-manager bg-neutral-700 p-6 rounded shadow-md mt-6">
        <div class="flex justify-between items-center mb-4">
            <h2 class="text-xl font-semibold text-neutral-100">{{ t('player_manager.title') }}</h2>
            <button @click="fetchPlayers" class="text-blue-400 hover:text-blue-300">
                {{ t('player_manager.refresh') }}
            </button>
        </div>

        <div v-if="loading" class="text-neutral-400">{{ t('player_manager.loading') }}</div>
        
        <table v-else class="w-full text-left border-collapse">
            <thead>
                <tr class="border-b border-neutral-600 text-neutral-300">
                    <th class="py-2">Player</th>
                    <th class="py-2">Ping</th>
                    <th class="py-2 text-right">Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="player in players" :key="player.uuid" class="border-b border-neutral-600/50">
                    <td class="py-3 flex items-center">
                        <img :src="`https://crafatar.com/avatars/${player.uuid}?size=32`" class="w-8 h-8 rounded mr-3" />
                        {{ player.name }}
                    </td>
                    <td class="py-3 text-neutral-400">{{ player.ping }}ms</td>
                    <td class="py-3 text-right space-x-2">
                        <button @click="executeAction('kick', player.name)" class="text-xs bg-yellow-600 hover:bg-yellow-500 px-2 py-1 rounded text-white">Kick</button>
                        <button @click="executeAction('ban', player.name)" class="text-xs bg-red-600 hover:bg-red-500 px-2 py-1 rounded text-white">Ban</button>
                    </td>
                </tr>
                <tr v-if="players.length === 0">
                    <td colspan="3" class="py-4 text-center text-neutral-400">{{ t('player_manager.no_players') }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useI18n } from 'vue-i18n';
import http from '@/api/http';
import { useRoute } from 'vue-router';

const { t } = useI18n();
const route = useRoute();
const serverId = route.params.id;

const players = ref([]);
const loading = ref(true);

const fetchPlayers = async () => {
    loading.value = true;
    try {
        const { data } = await http.get(`/api/client/servers/${serverId}/ultimate-suite/players`);
        players.value = data.data;
    } catch (error) {
        console.error('Failed to fetch players:', error);
    } finally {
        loading.value = false;
    }
};

const executeAction = async (command: string, playerName: string) => {
    try {
        await http.post(`/api/client/servers/${serverId}/ultimate-suite/players/command`, {
            command: command,
            player: playerName
        });
        alert(`${command} executed for ${playerName}`);
        fetchPlayers();
    } catch (error) {
        console.error('Action failed:', error);
    }
};

onMounted(() => {
    fetchPlayers();
    // Optional polling:
    // setInterval(fetchPlayers, 10000);
});
</script>

// UltimateSuite/resources/scripts/components/server/UltimateSuite/PlayerList.tsx
import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { ServerContext } from '@/state/server';
import { Spinner } from '@/components/elements/Spinner';
import { useFlash } from '@/plugins/useFlash';
import ConfirmationModal from '@/components/elements/ConfirmationModal';
import { useTranslation } from 'react-i18next';

interface Player {
    name: string;
    uuid: string;
    ping: number;
}

const PlayerList = () => {
    const { t } = useTranslation();
    const { addFlash } = useFlash();
    const uuid = ServerContext.useStoreState((state: any) => state.server.data!.uuid);
    
    const [players, setPlayers] = useState<Player[]>([]);
    const [loading, setLoading] = useState<boolean>(true);
    const [action, setAction] = useState<{ type: string, player: string } | null>(null);

    const fetchPlayers = () => {
        setLoading(true);
        axios.get(`/api/client/servers/${uuid}/ultimate-suite/players`)
            .then(({ data }: { data: { data: Player[] } }) => setPlayers(data.data))
            .catch(() => addFlash({ type: 'error', key: 'us:p', message: t('ultimate_suite.players.error_fetch') }))
            .finally(() => setLoading(false));
    };

    useEffect(() => { 
        fetchPlayers(); 
    }, [uuid]);

    const executeAction = () => {
        if (!action) return;
        axios.post(`/api/client/servers/${uuid}/ultimate-suite/players/command`, { command: action.type, player: action.player })
            .then(() => { 
                addFlash({ type: 'success', key: 'us:p', message: t('ultimate_suite.players.success_action', { action: action.type, player: action.player }) }); 
                fetchPlayers(); 
            })
            .catch(() => addFlash({ type: 'error', key: 'us:p', message: t('ultimate_suite.players.error_action') }))
            .finally(() => setAction(null));
    };

    return (
        <div className={'bg-neutral-800 p-6 rounded shadow-md border border-neutral-700 mt-4'}>
            <ConfirmationModal 
                visible={!!action} 
                title={t('ultimate_suite.players.confirm_title', { action: action?.type })} 
                buttonText={t('ultimate_suite.players.confirm_btn', { action: action?.type })} 
                onConfirmed={executeAction} 
                onDismissed={() => setAction(null)}
            >
                {t('ultimate_suite.players.confirm_msg', { action: action?.type, player: action?.player })}
            </ConfirmationModal>
            <div className={'flex justify-between items-center mb-6'}>
                <h2 className={'text-xl font-bold text-neutral-100'}>{t('ultimate_suite.players.title')}</h2>
                <button onClick={fetchPlayers} className={'bg-primary-600 hover:bg-primary-500 text-white px-3 py-1 rounded text-sm transition'}>
                    {t('ultimate_suite.players.refresh')}
                </button>
            </div>
            {loading ? <Spinner size={'small'} centered /> : (
                <table className={'w-full text-neutral-200'}>
                    <thead><tr className={'text-left border-b border-neutral-700'}><th className={'pb-3'}>Player</th><th className={'pb-3 text-right'}>Actions</th></tr></thead>
                    <tbody>
                        {players.map((p: Player) => (
                            <tr key={p.uuid} className={'border-b border-neutral-700/50'}>
                                <td className={'py-3'}>{p.name}</td>
                                <td className={'py-3 text-right'}>
                                    <button onClick={() => setAction({ type: 'kick', player: p.name })} className={'bg-yellow-600/20 text-yellow-500 px-2 py-1 rounded text-xs'}>Kick</button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            )}
        </div>
    );
};

export default PlayerList;
